---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-aurora
# description will be included in the image's metadata
description: This is my personal OS image.
alt-tags:
  - stable
  - latest

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: stable-daily # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - nix.sh
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: akmods
    base: bazzite
    #install:
    #  - evdi
  - type: bling
    install:
      - rpmfusion
  - type: rpm-ostree
    install:
    - https://updates.safing.io/latest/linux_amd64/packages/Portmaster-2.0.23-1.x86_64.rpm
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        - com.brave.Browser
        - it.mijorus.gearlever
        - dev.deedles.Trayscale
        - org.onlyoffice.desktopeditors
        - io.github.celluloid_player.Celluloid
        - org.gnome.Lollypop
        - org.kde.gwenview
        - io.github.flattool.Warehouse
        - io.github.dvlv.boxbuddyrs
        - org.gnome.Boxes
      - scope: user # Also add Flathub user repo, but no user packages
  - type: systemd
    system:
      enabled:
        - portmaster.service    
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
