---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: custom-aurora
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: script
    scripts:
      - nix.sh
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
        - com.brave.Browser
        - it.mijorus.gearlever
        - dev.deedles.Trayscale
        - org.onlyoffice.desktopeditors
        - io.github.celluloid_player.Celluloid
        - org.gnome.Lollypop
        - org.kde.gwenview
      - scope: user # Also add Flathub user repo, but no user packages
        - org.gpodder.gpodder
        - com.makemkv.MakeMKV
        - fr.handbrake.ghb
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
